// <auto-generated />
namespace DealershipApi.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ChangeDateTimeToDateTime2BecauseEFDidntDoItinTheFirstPlaceLikeItShouldHave : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangeDateTimeToDateTime2BecauseEFDidntDoItinTheFirstPlaceLikeItShouldHave));
        
        string IMigrationMetadata.Id
        {
            get { return "202202022154432_ChangeDateTimeToDateTime2BecauseEFDidntDoItinTheFirstPlaceLikeItShouldHave"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
